"""
Задание 4.

Для этой задачи:
1) придумайте 2-3 решения (не менее двух)
2) оцените сложность каждого решения в нотации О-большое
3) сделайте вывод, какое решение эффективнее и почему

Сама задача:
Пользователи веб-ресурса проходят аутентификацию.
В системе хранятся логин, пароль и отметка об активации учетной записи.

Нужно реализовать проверку, может ли пользователь быть допущен к ресурсу.
При этом его учетка должна быть активирована.
А если нет, то польз-лю нужно предложить ее пройти.

Приложение должно давать ответы на эти вопросы и быть реализовано в виде функции.
Для реализации хранилища можно применить любой подход,
который вы придумаете, например, реализовать словарь.

Примечание:
Без выполнения пунктов 2 и 3 задание считается нерешенным. Пункты 2 и 3 можно выполнить
через строки документации в самом коде.
Прошу вас внимательно читать ТЗ и не забыть выполнить все пункты.

Задание творческое. Здесь нет жестких требований к выполнению.
"""

#Решение 1 более эффективное, так как проверяет пароль и логин сразу в заданном значении,
# в то время как во второй реализации кода проходит по значениям и ищет совпадения.


data = {'Ivan Sergeev': ['ivan.sergeev@gmail.com', 'erkf2010', 1],
        'Sergey Petrov': ['petrov@yandex.ru', '1234df', 0],
        'Alina Ivanova': ['alinchik77@mail.ru', 'krasotka', 0]}


# Ищем пользователей с не активной учеткой (применяется для двух реализаций)

# 0(n log n)

for k, v in data.items():
    if v[-1] == 0:
        print(f'Пользователь {k} не активирован. Пожалуйста, введите логин и пароль.')


# Сложность 0(log n)

def access(login, password):
    a = data.get('Sergey Petrov')
    if a[0] == login and a[1] == password:
        print(f'Доступ разрешен. Ваш логин {login}, пароль {password}.')
    else:
        print(f'У вас ошибка. Попробуйте еще раз')


access('petrov@yandex.ru', '1234df')

# Сложность O(n)

def verify(login, password):
    for i in data.get('Alina Ivanova'):
        try:
            if login and password in i:
                print('Ура. Вы прошли аутентификацию')  # выдается ошибка typeerror, а также из-за 0 в значении выдает, что пользователь не прошел. Подскажите, пожалуйста, где ошибка.
        except TypeError:
            pass

verify('alinchik77@mail.ru', 'krasotka')
